FROM php:8.2-fpm-buster

RUN apt-get update && apt-get install -y

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY src/ /var/www/symfony
WORKDIR /var/www/symfony