version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
        networks:
            symfony:
                aliases:
                    - shared-data:/var/www/symfony/public

    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:80
        networks:
            symfony:
                aliases:
                    - shared-data:/var/www/symfony/public
        depends_on:
            - php

networks:
    symfony:
