version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
          APP_ENV: dev
        volumes:
            - ./src/:/var/www/symfony
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./src/:/var/www/symfony
        ports:
            - 8080:80
        networks:
            - symfony

volumes:
    symfony_app_var:
    symfony_app_vendor:

networks:
    symfony: